### ISSUE TITLE
vectorize this block

### ISSUE THREAD

**Issue by glyg** [TigiGln/OTAnalysis#3]
I think this [code](https://github.com/TigiGln/OTAnalysis/blob/db17f2c013ffa1c875e9b2f8ff0c555d4cfccfa6/otanalysis/model/class_curve.py#L307-L311) can be easily vectorized with boolean indexing:
```python
index_data_min = data.nonzero((abs(data -force) > interval) &  (data < data_min_approach))[-1]
```

**Comment by TigiGln** [comment]
Good ideas but delete code
